repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--remove-unused-variables", "--remove-all-unused-imports"]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
