name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Clone and install face-detection and l2cs
      run: |
        pip install git+https://github.com/elliottzheng/face-detection@786fbab7095623c348e251f1f0a8b323721c6a84
        pip install git+https://github.com/edavalosanaya/L2CS-Net.git@4a0f978d5b4c426a7d37022d8c927d6ea031dcb6

    - name: Install other dependencies
      run: |
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        flake8 src/ --max-line-length=79
      continue-on-error: false

    - name: Run unit tests
      run: |
        pytest tests/
